package com.example.spring.config.dto

enum class ErrorCode {
    UNKNOWN_ERROR,
    INVALID_PARAMETER,
    ITEM_NOT_EXIST,
    WRONG_PASSWORD,
    ACCESS_TOKEN_EXPIRED,
    REFRESH_TOKEN_EXPIRED,
    DATA_NOT_FOUND,
    INTERNAL_SERVER_ERROR,
    ALREADY_EXIST
}